### ISSUE TITLE
Descobrir a razão de python setup.py test estar falhando

### ISSUE THREAD

**Issue by cuducos** [cuducos/calculadora-do-cidadao#17]
Ao executar `python setup.py test` o [Black](https://github.com/psf/Black) falha com:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/calculadora-do-cidadao/calculadora-do-cidadao/.eggs/black-19.3b0-py3.8.egg/black.py", line 79, in <module>
    pygram.initialize(CACHE_DIR)
  File "/home/runner/work/calculadora-do-cidadao/calculadora-do-cidadao/.eggs/black-19.3b0-py3.8.egg/blib2to3/pygram.py", line 41, in initialize
    python_grammar = driver.load_packaged_grammar("blib2to3", _GRAMMAR_FILE,
  File "/home/runner/work/calculadora-do-cidadao/calculadora-do-cidadao/.eggs/black-19.3b0-py3.8.egg/blib2to3/pgen2/driver.py", line 198, in load_packaged_grammar
    gp = _generate_pickle_name(grammar_source, cache_dir) if cache_dir else None
  File "/home/runner/work/calculadora-do-cidadao/calculadora-do-cidadao/.eggs/black-19.3b0-py3.8.egg/blib2to3/pgen2/driver.py", line 151, in _generate_pickle_name
    return os.path.join(cache_dir, os.path.basename(name))
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not PosixPath
```

Esse erro não ocorre se instalamos as dependências e rodamos `pytest`.

**Comment by cuducos** [comment]
Não vale a pena explorar esse bug, já que `python setup.py test` vai ser descontinuado. Foco na alternativa proposta na _issue_ #19 (deixando essa _issue_ aberta só para registro, enquanto o comando documentado, da `master` e da CI ainda está falhando).
