### ISSUE TITLE
Exportação de todos os dados

### ISSUE THREAD

**Issue by cnd07** [cuducos/calculadora-do-cidadao#38]
Olá!
Com Python 3.8.3+, tentando exportar os dados de todos os índices (adaptadores) de uma vez só, tenho o seguinte resultado, aqui:

jhh@jhhc:~$ python -m calculadora_do_cidadao
[1 of 7] Exporting ALLURBANCITYAVERAGE data…
Traceback (most recent call last):
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/__main__.py", line 44, in <module>
    cli()
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/typer/main.py", line 213, in __call__
    return get_command(self)()
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/typer/main.py", line 496, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/__main__.py", line 39, in export
    table = import_from_dicts(data())
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/rows/plugins/dicts.py", line 35, in import_from_dicts
    for index, row in enumerate(data, start=1):
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/__main__.py", line 33, in data
    yield from adapter().export(include_name=True)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/adapters/__init__.py", line 64, in __init__
    self.data = {key: value for key, value in self.download()}
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/adapters/__init__.py", line 64, in <dictcomp>
    self.data = {key: value for key, value in self.download()}
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/calculadora_do_cidadao/adapters/__init__.py", line 176, in download
    for data in self.read_from(path, **kwargs):
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/rows/plugins/xls.py", line 165, in import_from_xls
    book = xlrd.open_workbook(filename, formatting_info=True)
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/xlrd/__init__.py", line 148, in open_workbook
    bk = book.open_workbook_xls(
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/xlrd/book.py", line 82, in open_workbook_xls
    bk.biff2_8_load(
  File "/home/jhh/.pyenv/versions/3.8-dev/lib/python3.8/site-packages/xlrd/book.py", line 616, in biff2_8_load
    raise XLRDError("File size is 0 bytes")
xlrd.biffh.XLRDError: File size is 0 bytes

**Comment by cuducos** [comment]
> Com Python 3.8.3+, tentando exportar os dados de todos os índices (adaptadores) de uma vez só

Isso acontece apenas quanto tenta com _todos_? Ou se tu tenta cada um em isolado o erro acontece com todos?

Digo isso pois na saída que você colou, o erro acontece quanto tenta-se baixar _FED’s Consumer Price Index for All Urban Consumers_… então talvez o endereço ou API desse indicador em específico tenha mudado.

Se voce tiver disponibilidade, tente um por vez e veja se o erro persiste em todos os indicadores. Isso ajuda a afunilar o problema : )

**Comment by cnd07** [comment]
Certamente!
Como eu faço para para exportar somente um índice a partir da linha de comando?
Tentei aqui 
$ python calculadora_do_cidadao.Selic 
$ python -m calculadora_do_cidadao.Selic
Mas não é isso :)

**Comment by cuducos** [comment]
> Como eu faço para para exportar somente um índice a partir da linha de comando?

Boa pergunta, que me leva a perguntar outra de volta: pq você está tentando exportar todos os índices com `python -m calculadora_do_cidadao`? Tem isso documentado em algum lugar? Sinceramente não lembro e fiquei na dúvida se é assim que funciona.

**Comment by cnd07** [comment]
`python -m calculadora_do_cidadao` está documentado  no [site do projeto](https://calculadora-do-cidadao.readthedocs.io/pt_BR/latest/usage.html)

**Comment by cuducos** [comment]
Ah, perfeito! Muito obrigado por refrescar a memória aqui. Realmente não tem como, pela linha de comando, exportar um ou outro. Teria que ser com um script mesmo, com essas [6 linhas aqio](https://calculadora-do-cidadao.readthedocs.io/pt_BR/latest/usage.html#uso).

**Comment by cuducos** [comment]
Parece que o adaptador `AllUrbanCityAverage` não funciona mais. Os outros, exportam normal. Vou criar uma _issue_ específica par a isso, ok?

**Comment by cuducos** [comment]
@cnd07 acabei de soltar uma nova versão, `pip install --upgrade calculadora-do-cidadao` para baixar a 0.4.2 e teste aí : )

**Comment by cnd07** [comment]
> @cnd07 acabei de soltar uma nova versão, `pip install --upgrade calculadora-do-cidadao` para baixar a 0.4.2 e teste aí : )

Eu rodei o script somente da Selic, e deu certo na versão anterior. Fiz o upgrade e, para todos os índices, deu certo também.
Muito obrigado!

**Comment by cuducos** [comment]
Boa! Obrigado demais por reportar o erro : )
